version: '3.8'
services:
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - surge:/data/db
  backend:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      MONGO_URI: mongodb://surge
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
volumes:
  surge:
