version: '3.8'
services:  
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 3001:3001
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017/surge
  db:
    image: mongo:4.4.4
    ports:
      - 27017:27017
    volumes:
      - surge:/data/db
volumes:
  surge:
